FROM java:8
ENV MYSQL_SERVER="" \
    REDIS_SERVER=""
COPY ofilm-service-0.0.1-SNAPSHOT.jar app.jar
COPY Soldier /home/server/static/Soldier
COPY f63b0f38-b65d-4a8c-9ff7-6772db0eca48.jpg /home/server/static/f63b0f38-b65d-4a8c-9ff7-6772db0eca48.jpg